# Сергей Зотов AIN-2-22

In [1]:
import numpy as np

### Пример 1

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

### Пример 2

In [3]:
b = np.array([[1.3, 2.4], [0.3, 4.1]])
b

array([[1.3, 2.4],
       [0.3, 4.1]])

### Пример 3

In [4]:
c = np.array([[1,2,3], [4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

### Пример 4

In [5]:
d = np.array(((1,2,3), (4,5,6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

### Пример 5

In [6]:
e = np.array([(1,2,3), [4,5,6], (7,8,9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Пример 6

In [7]:
f = np.array(((1,2,3), (4,5,6)), dtype=float)
f

array([[1., 2., 3.],
       [4., 5., 6.]])

### Пример 7

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Пример 8

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Пример 9

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Пример 10

In [11]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

### Пример 11

In [12]:
np.arange(0, 12, 3)

array([0, 3, 6, 9])

### Пример 13

In [13]:
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

### Пример 13

In [17]:
!pip install --upgrade numpy

In [4]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Пример 14

In [6]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Пример 15

In [7]:
np.random.random(3)

array([0.86145339, 0.45141109, 0.45140751])

### Пример 16

In [8]:
np.random.random((3,3))

array([[0.65443385, 0.55644046, 0.89806211],
       [0.27208487, 0.53332643, 0.61417973],
       [0.19862626, 0.86713587, 0.2076466 ]])

### Пример 17

In [9]:
d = np.array(((1,2,3), (4,5,6), (7,8,9)), dtype=float)
d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [10]:
d[::-1] # перестановка строк

array([[7., 8., 9.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [11]:
d[:,2] # третий столбец

array([3., 6., 9.])

In [12]:
d[1,2] = 10
d

array([[ 1.,  2.,  3.],
       [ 4.,  5., 10.],
       [ 7.,  8.,  9.]])

In [13]:
for i in d:
    print(i ** 0.5)

[1.         1.41421356 1.73205081]
[2.         2.23606798 3.16227766]
[2.64575131 2.82842712 3.        ]


# Лабораторная работа №2
## Работа с библиотеками NumPy, pandas

In [14]:
import numpy as np

In [15]:
# Создание массива (ndarray) из списка (list)
list_1 = [0,1,2,3,4]
arr_1d = np.array(list_1)
print(arr_1d)
print(arr_1d.dtype)
type(arr_1d)

[0 1 2 3 4]
int64


numpy.ndarray

In [16]:
# Проверка размерности массив
b = np.array([[0,1,2,3], [4,5,6,7]])
b.shape

(2, 4)

In [17]:
# Создание массива из последовательности кортежей
b = np.array([(1.3, 2.4), (0.3, 4.1)])
b

array([[1.3, 2.4],
       [0.3, 4.1]])

In [18]:
# Арифметические действия с массивами
for i in range(len(list_1)):
    list_1[i] += 1

arr_1d += 1

print(list_1)
print(arr_1d)

for i in range(len(list_1)):
    list_1[i] -= 1

arr_1d -= 1

print(list_1)
print(arr_1d)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [19]:
# Дополнительные возможности получения массивов с помощью функций zeros(), ones(), arrange(), linspace()
zeros = np.zeros(10)
ones = np.ones(10)
arange_1 = np.arange(10)
linspace_1 = np.linspace(0, 1, 5)

print('zeros', zeros)
print('ones', ones)
print('arange_1', arange_1)
print('linspace_1', linspace_1)

zeros [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ones [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
arange_1 [0 1 2 3 4 5 6 7 8 9]
linspace_1 [0.   0.25 0.5  0.75 1.  ]


In [20]:
print(ones + arange_1)
print(ones * arange_1)
print(ones / arange_1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


C:\Users\Sergey\AppData\Local\Temp\ipykernel_26912\881108093.py:3: RuntimeWarning: divide by zero encountered in divide
  print(ones / arange_1)


In [22]:
# Индексация и двумерные массивы
print(np.arange(10)[5:9])

arange = np.arange(10).reshape(2, 5)

print('arange1 = ', arange)
print('arange2 = ', arange[:, 3:])

print('arange3 = ', arange[arange%2 == 1])

[5 6 7 8]
arange1 =  [[0 1 2 3 4]
 [5 6 7 8 9]]
arange2 =  [[3 4]
 [8 9]]
arange3 =  [1 3 5 7 9]


In [25]:
# Применение метода np.newaxis
a = np.arange(6)
print(a.shape)

a2 = a[np.newaxis, :]
a2.shape

(6,)


(1, 6)

## Pandas

In [26]:
import pandas as pd

df = pd.DataFrame({'int_col' : [1,2,6,8,-1], 'float_col' : [0.1, 0.2, 0.2, 10.1, None], 'str_col' : ['a', 'b', None, 'c', 'a']})

df

int_col  float_col str_col
0        1        0.1       a
1        2        0.2       b
2        6        0.2    None
3        8       10.1       c
4       -1        NaN       a

In [27]:
cities = {"name" : ["London","Berlin", "Madrid", "Rome","Paris", "Vienna", "Bucharest", "Hamburg","Budapest", "Warsaw", "Barcelona","Munich", "Milan"],
          "population": [8615246, 3562166, 3165235, 2874038,2273305, 1805681, 1803425, 1760433,1754000, 1740119, 1602386, 1493900, 1350680],
          "area": [1572, 891.85, 605.77, 1285,105.4, 414.6, 228, 755,525.2, 517, 101.9, 310.4,181.8]
          }
city_frame = pd.DataFrame(cities, columns=["population", "area"], index=cities["name"])
print (city_frame)

           population     area
London        8615246  1572.00
Berlin        3562166   891.85
Madrid        3165235   605.77
Rome          2874038  1285.00
Paris         2273305   105.40
Vienna        1805681   414.60
Bucharest     1803425   228.00
Hamburg       1760433   755.00
Budapest      1754000   525.20
Warsaw        1740119   517.00
Barcelona     1602386   101.90
Munich        1493900   310.40
Milan         1350680   181.80


In [28]:
# индексация
df.loc[:, ['float_col', 'int_col']]

float_col  int_col
0        0.1        1
1        0.2        2
2        0.2        6
3       10.1        8
4        NaN       -1

In [29]:
# Импорт данных из .csv
df = pd.read_csv('Global Population Trends(2016-2022).csv')
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55              63      37.342       7.027   
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38              61      32.516       8.266   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[1073 rows x 12 columns]

In [30]:
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55              63      37.342       7.027          5.129   
1                 56              63      36.927       6.981          5.002   
2                 58              64      36.466       6.791           4.87   
3                 60              63      36.051       7.113           4.75   
4                  -              62      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8           3  
2                  46.3           3  
3                  44.8           3  
4                  43.4           3

In [31]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

In [32]:
# Описательная статистика
df.describe()

Year   Birth Rate   Death Rate
count  1073.000000  1073.000000  1073.000000
mean   2019.013048    18.801519     7.841907
std       1.410190     9.903449     2.973418
min    2017.000000     0.000000     0.000000
25%    2018.000000    10.620000     6.067000
50%    2019.000000    16.025000     7.396000
75%    2020.000000    25.921000     9.313000
max    2021.000000    46.351000    21.700000

In [33]:
df.describe(include=['object', 'bool'])

Country Total Population Urban Population Rural Population  \
count          1073             1073             1073             1073   
unique          216              865              856              817   
top     Afghanistan                -                -                -   
freq              5              209              217              257   

       Population Density Life Expectancy Fertility Rate  \
count                1073            1073           1073   
unique                350              36            774   
top                     -              74              -   
freq                  223              63             24   

       Infant Mortality Rate Growth Rate  
count                   1073        1073  
unique                   438          11  
top                        -           1  
freq                     101         255

In [34]:
df.Country.value_counts()

Country
Afghanistan                 5
Albania                     5
Algeria                     5
Angola                      5
Argentina                   5
                           ..
American Samoa              4
Channel Islands             4
Monaco                      4
Northern Mariana Islands    4
San Marino                  4
Name: count, Length: 216, dtype: int64

In [35]:
# Описание переменных
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


In [37]:
# Преобразовать данные из столбца в список значений
print(df['Country'].tolist())

['Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Albania', 'Albania', 'Albania', 'Albania', 'Albania', 'Algeria', 'Algeria', 'Algeria', 'Algeria', 'Algeria', 'American Samoa', 'American Samoa', 'American Samoa', 'American Samoa', 'Andorra', 'Andorra', 'Andorra', 'Andorra', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'Antigua And Barbuda', 'Antigua And Barbuda', 'Antigua And Barbuda', 'Antigua And Barbuda', 'Antigua And Barbuda', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina', 'Armenia', 'Armenia', 'Armenia', 'Armenia', 'Armenia', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Australia', 'Australia', 'Australia', 'Australia', 'Australia', 'Austria', 'Austria', 'Austria', 'Austria', 'Austria', 'Azerbaijan', 'Azerbaijan', 'Azerbaijan', 'Azerbaijan', 'Azerbaijan', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahrain', 'Bangladesh', 'Bangladesh', 'Bangladesh', 'Bangladesh', 'Bangladesh'

In [38]:
# Сортировка
df = df.sort_values(by='Country', ascending=False)
df.head()

Country  Year Total Population Urban Population Rural Population  \
1072  Zimbabwe  2021       15,993,524        5,166,388       10,827,136   
1071  Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1070  Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1069  Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1068  Zimbabwe  2017                -                -                -   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1072                  -              59      30.537       9.057   
1071                 41              61      31.009       8.132   
1070                 40              61      31.518       8.043   
1069                 39              61      32.074       7.972   
1068                 38              61      32.516       8.266   

     Fertility Rate Infant Mortality Rate Growth Rate  
1072          3.491                  35.7           2  
1071          3.545                  36.6           2  
1070          3.599                  37.1           2  
1069          3.659                    38           2  
1068          3.706                  39.5           -

In [39]:
#Вызов команд sum(), mean(), groupby(). Создание фрейма данных
beverages = pd.DataFrame({'Name': ['Robert', 'Melinda', 'Brenda', 'Samantha', 'Melinda', 'Robert',
'Melinda', 'Brenda', 'Samantha'], 'Coffee': [3, 0, 2, 2, 0, 2, 0, 1, 3], 'Tea': [10, 4, 2, 0, 3, 0, 3, 2,
0]})
beverages

Name  Coffee  Tea
0    Robert       3   10
1   Melinda       0    4
2    Brenda       2    2
3  Samantha       2    0
4   Melinda       0    3
5    Robert       2    0
6   Melinda       0    3
7    Brenda       1    2
8  Samantha       3    0

In [40]:
# Вызов функции sum()
beverages ['Coffee'].sum()

np.int64(13)

In [41]:
beverages [['Coffee', 'Tea']].sum()

Coffee    13
Tea       24
dtype: int64

In [42]:
# Применение группировки данных
res = beverages.groupby(['Name']).sum()
print(res)

          Coffee  Tea
Name                 
Brenda         3    4
Melinda        0   10
Robert         5   10
Samantha       5    0


In [43]:
beverages.groupby(['Name']).mean()

Coffee       Tea
Name                      
Brenda       1.5  2.000000
Melinda      0.0  3.333333
Robert       2.5  5.000000
Samantha     2.5  0.000000

In [46]:
data = {
    'First Name': ['John', 'Emily', 'Michael', 'Sarah', 'David', 'Anna', 'James'],
    'Last Name': ['Smith', 'Johnson', 'Brown', 'Williams', 'Jones', 'Davis', 'Miller'],
    'Country': ['USA', 'USA', 'UK', 'Australia', 'Germany', 'France', 'Italy'],
    'Age': [28, 34, 29, 22, 45, 31, 37]
}
df2 = pd.DataFrame(data)
df2

First Name Last Name    Country  Age
0       John     Smith        USA   28
1      Emily   Johnson        USA   34
2    Michael     Brown         UK   29
3      Sarah  Williams  Australia   22
4      David     Jones    Germany   45
5       Anna     Davis     France   31
6      James    Miller      Italy   37

In [49]:
# Отбор данных по условию
print(df2[df2['Country'] == 'USA'])
print('-'*20)
print(df2[(df2['Country'] == 'USA') & (df2['Age'] == 34)])

  First Name Last Name Country  Age
0       John     Smith     USA   28
1      Emily   Johnson     USA   34
--------------------
  First Name Last Name Country  Age
1      Emily   Johnson     USA   34


### Экспорт данных в формат MS Excel

In [50]:
# базовый экспорт
df2.to_excel(r'C:\Users\Sergey\PycharmProjects\BigData\mydata.xlsx')

In [51]:
# экспорт без индекса
df2.to_excel(r'C:\Users\Sergey\PycharmProjects\BigData\mydata.xlsx', index=False)

In [52]:
# экспорт без индекса и заголовка
df2.to_excel(r'C:\Users\Sergey\PycharmProjects\BigData\mydata.xlsx', index=False, header=False)

In [53]:
# экспорт и имя листа
df2.to_excel(r'C:\Users\Sergey\PycharmProjects\BigData\mydata.xlsx', sheet_name='this_data')

# Задания
## Использование команд библиотеки NumPy

### 1. Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [55]:
arr = np.arange(5, 101, 5)
print(arr)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


### 2. Из полученного массива получить массив с кратными 10 числами

In [56]:
arr10 = arr[arr % 10 == 0]
print(arr10)

[ 10  20  30  40  50  60  70  80  90 100]


### 3. Получить двумерный массив с двумя столбцами

In [60]:
arr2d = arr.reshape(-1, 2)
arr2d

array([[  5,  10],
       [ 15,  20],
       [ 25,  30],
       [ 35,  40],
       [ 45,  50],
       [ 55,  60],
       [ 65,  70],
       [ 75,  80],
       [ 85,  90],
       [ 95, 100]])

### 4. Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [61]:
my_second_array = arr - 5
my_second_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

### 5. Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы

In [65]:
combined_arr = np.hstack((arr2d, my_second_array.reshape(-1,2))).T
combined_arr

array([[  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95]])

### 6. Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [69]:
result = combined_arr.copy()
result[1:3] = result[1:3] / arr[:2, np.newaxis]
result

array([[ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95]])

### 7. Оставить только те значения, которые не изменились после деления

In [72]:
before_division = combined_arr.copy()
result = combined_arr.copy()
result[1:3] = result[1:3] / arr[:2, np.newaxis]
unchanged = np.where(result == before_division, result, np.nan)

unchanged

array([[ 5., 15., 25., 35., 45., 55., 65., 75., 85., 95.],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [ 0., nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [ 5., 15., 25., 35., 45., 55., 65., 75., 85., 95.]])

### 8. Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

In [73]:
array_2d_3 = combined_arr[:3]
array_2d_3

array([[  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90]])

In [74]:
array_2d_3[[0, 2]] = array_2d_3[[2, 0]]
array_2d_3

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95]])

### 9. Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().

In [75]:
mean_value = np.mean(array_2d_3, axis=1)
median_value = np.median(array_2d_3, axis=1)
std = np.std(array_2d_3, axis=1)

print(f"Среднее: {mean_value}")
print(f"Медиана: {median_value}")
print(f"Станд. отклонение: {std}")

Среднее: [45. 55. 50.]
Медиана: [45. 55. 50.]
Станд. отклонение: [28.72281323 28.72281323 28.72281323]


### 10. Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк

In [76]:
norm_arr = array_2d_3 / array_2d_3.max(axis=1)[:, np.newaxis]
norm_arr

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.1       , 0.2       , 0.3       , 0.4       , 0.5       ,
        0.6       , 0.7       , 0.8       , 0.9       , 1.        ],
       [0.05263158, 0.15789474, 0.26315789, 0.36842105, 0.47368421,
        0.57894737, 0.68421053, 0.78947368, 0.89473684, 1.        ]])

## Использование команд библиотеки pandas
### 1. Импортируйте данные из файла “Global Population Trends(2016-2022).csv”.

In [77]:
import pandas as pd
data = pd.read_csv('Global Population Trends(2016-2022).csv')
data

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55              63      37.342       7.027   
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38              61      32.516       8.266   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[1073 rows x 12 columns]

### 2. Считайте несколько первых записей таблицы

In [78]:
data.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55              63      37.342       7.027          5.129   
1                 56              63      36.927       6.981          5.002   
2                 58              64      36.466       6.791           4.87   
3                 60              63      36.051       7.113           4.75   
4                  -              62      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8           3  
2                  46.3           3  
3                  44.8           3  
4                  43.4           3

### 3. Определите размерность данного фрейма

In [79]:
data.shape()

(1073, 12)

### 4. Выведите название заголовков столбцов фрейма

In [80]:
data.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

### 5. Получите описание всех переменных

In [82]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


### 6. Удалите строки, не содержащие значения в столбце «Total Population» - “-”

In [83]:
data2 = data[data['Total Population'] != '-']
data2

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
6                   105              79      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -              61      34.511       6.973   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
6              1.44                   8.3           0  
...             ...                   ...         ...  
1067          4.308                  40.2           3  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[864 rows x 12 columns]

### 7. Получите описательную статистику по переменным (например, max(), min(), describe())

In [84]:
data2.max()

Country                    Zimbabwe
Year                           2021
Total Population             99,258
Urban Population         99,876,265
Rural Population            998,397
Population Density               99
Life Expectancy                  85
Birth Rate                   46.127
Death Rate                     21.7
Fertility Rate                7.023
Infant Mortality Rate           9.9
Growth Rate                       5
dtype: object

In [85]:
data2.describe()

Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000

### 8. Выполните сортировку данных по нескольким критериям

In [87]:
data2 = data2.sort_values(by=['Country', 'Year', 'Birth Rate'])
data2

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
6                   105              79      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -              61      34.511       6.973   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
6              1.44                   8.3           0  
...             ...                   ...         ...  
1067          4.308                  40.2           3  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[864 rows x 12 columns]

### 9. Выведите название страны, которая имеет максимальную численность населения

In [98]:
data2['Total Population'] = data2['Total Population'].str.replace(',','').astype(int)
max_population = data2['Total Population'].max()
mp_country = data2.loc[data2['Total Population'] == max_population, 'Country'].values[0]
print(mp_country)

China


### 10. Выведите название страны, которая имеет минимальную численность населения

In [100]:
min_population = data2['Total Population'].min()
mp_country = data2.loc[data2['Total Population'] == min_population, 'Country'].values[0]
print(mp_country)

Tuvalu


### 11. Экспорт фрейма в MS Excel

In [101]:
data2.to_excel(r'C:\Users\Sergey\PycharmProjects\BigData\mydata.xlsx')